import type { Metadata } from "next";
import Link from "next/link";
import { Instrument_Serif, Inter, JetBrains_Mono } from "next/font/google";
import { getSummary } from "@/lib/data";
import { fmtInt } from "@/lib/format";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans-body",
});
const serif = Instrument_Serif({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--font-serif-display",
});
const mono = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mono-body",
});

export const metadata: Metadata = {
  title: "Accelerator Atlas",
  description:
    "A cross-accelerator analysis of Y Combinator, Entrepreneur First, South Park Commons, and a16z Speedrun.",
};

const NAV = [
  { href: "/", label: "Overview" },
  { href: "/explorer", label: "Explorer" },
  { href: "/batches", label: "Batches" },
  { href: "/founders", label: "Founders" },
  { href: "/survivorship", label: "Survivorship" },
  { href: "/insights", label: "Insights" },
  { href: "/data-quality", label: "Data Quality" },
  { href: "/about", label: "About" },
];

const FULL_DATASET_MAILTO =
  "mailto:sidkbohra@gmail.com?subject=Accelerator%20Atlas%20full%20dataset";

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const { sample } = await getSummary();
  return (
    <html lang="en" className={`${inter.variable} ${serif.variable} ${mono.variable}`}>
      <body>
        <div className="min-h-dvh flex flex-col">
          <header className="border-b hairline sticky top-0 z-20 bg-[var(--color-cream)]/90 backdrop-blur-sm">
            <div className="max-w-[1400px] mx-auto px-6 py-4 flex flex-wrap items-center justify-between gap-x-6 gap-y-3">
              <Link href="/" className="flex items-baseline gap-3 group">
                <span className="font-serif text-[26px] leading-none text-[var(--color-ink)] italic tracking-tight">
                  Accelerator Atlas
                </span>
                <span className="text-[11px] uppercase tracking-[0.18em] text-[var(--color-muted)] hidden sm:inline">
                  YC · EF · SPC · Speedrun
                </span>
              </Link>
              <nav className="flex flex-wrap items-center gap-x-1 gap-y-1">
                {NAV.map((n) => (
                  <Link
                    key={n.href}
                    href={n.href}
                    className="px-2.5 py-1.5 text-[13px] text-[var(--color-ink-2)] hover:text-[var(--color-accent)] hover:bg-[var(--color-accent-soft)] rounded-md transition-colors whitespace-nowrap"
                  >
                    {n.label}
                  </Link>
                ))}
              </nav>
            </div>
          </header>
          {sample && (
            <div className="border-b hairline bg-[var(--color-accent-soft)]">
              <p className="max-w-[1400px] mx-auto px-6 py-2.5 text-[13px] text-[var(--color-ink-2)]">
                Public demo: company lists show a {fmtInt(sample.n_companies)}-company sample of{" "}
                {fmtInt(sample.n_companies_total)}. Totals and charts cover the full dataset;
                founder-level data is not published.{" "}
                <a href={FULL_DATASET_MAILTO} className="underline text-[var(--color-accent)]">
                  Request the full dataset
                </a>
              </p>
            </div>
          )}
          <main className="flex-1">{children}</main>
          <footer className="border-t hairline mt-20">
            <div className="max-w-[1400px] mx-auto px-6 py-6 flex justify-between text-xs text-[var(--color-muted)]">
              <span>
                Static snapshot regenerated by{" "}
                <code className="font-mono">uv run python -m accelerator_atlas.export.to_json</code>
              </span>
              <span>Personal research. No warranties.</span>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
