import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

import { MetricCard } from "@/components/metric-card";
import { getInsights } from "@/lib/data";
import { fmtInt } from "@/lib/format";

import { InsightTabs } from "@/components/insights/insight-tabs";

export default async function InsightsPage() {
  const { insights, budget } = await getInsights();

  const ws = insights.find((i) => i.kind === "whitespace_report");
  const cohorts = insights.filter((i) => i.kind === "cohort_narrative");

  return (
    <div className="max-w-[1200px] mx-auto px-6 py-10">
      <header className="mb-8">
        <p className="text-[12px] uppercase tracking-[0.2em] text-[var(--color-accent)] mb-2">
          Insights
        </p>
        <h1 className="font-serif italic text-[48px] tracking-tight leading-[1.05] mb-3">
          What the data says, stitched together.
        </h1>
        <p className="text-[15px] text-[var(--color-ink-3)] max-w-2xl">
          Every narrative below was generated by Grok against a pivot computed
          from the DB. Regenerating is idempotent: unchanged inputs hit the
          on-disk cache at zero cost.
        </p>
      </header>

      <section className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-10">
        <MetricCard label="Calls" value={fmtInt(budget.calls)} />
        <MetricCard
          label="Spent"
          value={`$${budget.spent_usd.toFixed(4)}`}
          sub={`of $${budget.cap_usd.toFixed(0)} cap`}
        />
        <MetricCard
          label="Remaining"
          value={`$${budget.remaining_usd.toFixed(2)}`}
          accent
        />
        <MetricCard
          label="Total tokens"
          value={fmtInt(budget.prompt_tokens + budget.completion_tokens)}
          sub={`${fmtInt(budget.prompt_tokens)} in · ${fmtInt(budget.completion_tokens)} out`}
        />
      </section>

      {ws && (
        <section className="card p-8 mb-10">
          <div className="flex items-baseline justify-between mb-4">
            <h2 className="font-serif italic text-[30px] tracking-tight">
              White-space analysis
            </h2>
            <span className="text-[11px] text-[var(--color-muted)] font-mono">
              {ws.model}
            </span>
          </div>
          <article className="prose-atlas">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{ws.content}</ReactMarkdown>
          </article>
        </section>
      )}

      {cohorts.length > 0 && (
        <section className="card p-8 mb-10">
          <h2 className="font-serif italic text-[30px] tracking-tight mb-4">
            Per-accelerator narratives
          </h2>
          <InsightTabs insights={cohorts} />
        </section>
      )}

      {budget.by_purpose.length > 0 && (
        <section className="card p-6">
          <h2 className="font-serif italic text-[22px] tracking-tight mb-3">
            Ledger (by purpose)
          </h2>
          <table className="w-full text-sm">
            <thead className="text-[11px] uppercase tracking-[0.12em] text-[var(--color-muted)]">
              <tr>
                <th className="text-left py-2">Purpose</th>
                <th className="text-right py-2">Calls</th>
                <th className="text-right py-2">Cost</th>
                <th className="text-right py-2">Tokens (in / out)</th>
              </tr>
            </thead>
            <tbody>
              {budget.by_purpose.map((p) => (
                <tr key={p.purpose} className="border-t hairline">
                  <td className="py-2 font-mono text-[12px] text-[var(--color-ink-2)]">
                    {p.purpose}
                  </td>
                  <td className="py-2 text-right num-tabular">{p.calls}</td>
                  <td className="py-2 text-right num-tabular">
                    ${p.spent_usd.toFixed(4)}
                  </td>
                  <td className="py-2 text-right num-tabular text-[var(--color-muted)]">
                    {fmtInt(p.prompt_tokens)} / {fmtInt(p.completion_tokens)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      )}
    </div>
  );
}
